services:
  backend:
    build: ./backend
    env_file: ./backend/.env
    volumes:
      - uploads_data:/app/uploads
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build: ./front
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

volumes:
  uploads_data:

networks:
  app-network:
